# Generated by Django 4.1.7 on 2023-03-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("adress", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                ("cuisine_type", models.CharField(max_length=200)),
                ("is_vegetarian_friendly", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("number_of_persons", models.IntegerField()),
                ("type", models.CharField(max_length=200)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.customer",
                    ),
                ),
                (
                    "restaurant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("chef_specialty", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
        ),
    ]
