# Generated by Django 4.1.7 on 2023-04-10 19:28

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                max_length=100, validators=[restaurant.models.name_is_alphabetic]
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.IntegerField(
                validators=[restaurant.models.integer_poz_validator]
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateTimeField(validators=[restaurant.models.not_current_date]),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="number_of_persons",
            field=models.IntegerField(
                validators=[restaurant.models.capacity_validator]
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
